[package]
name = "pubsub-types"
description = "Core types, message envelope, and trait definitions for Cardano PubSub"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
ciborium = { workspace = true }
pallas-crypto = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
