name = "io-pubsub/node-registry"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'io-pubsub/node-registry'"

[repository]
user = "io-pubsub"
project = "node-registry"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
