[package]
name = "pubsub-network"
description = "Network layer implementations: Cyclon, Vicinity, Hybrid Dissemination, QUIC transport"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pubsub-types = { path = "../pubsub-types" }
tokio = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
ciborium = { workspace = true }
pallas-crypto = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
bytes = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
rcgen = "0.13"
serde_json = { workspace = true }

[features]
cardano = ["dep:pallas", "dep:reqwest", "dep:hex"]

[dependencies.pallas]
version = "0.34"
optional = true

[dependencies.reqwest]
version = "0.12"
features = ["json"]
optional = true

[dependencies.hex]
version = "0.4"
optional = true
